
spring.application.name=OfficeSystem

## MariaDB
spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/officesystem
spring.datasource.username=officesystem
spring.datasource.password=${DB_PASSWORD}

## JPA設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

## Thymeleaf
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

## ページング設定
pageRowCnt=5

# ログファイルの出力先とファイル名
logging.file.name=logs/myapp.log
 
# ログレベル（任意）
logging.level.root=INFO
